module.exports = [
    "Ouija",
    "Area 51",
    "Padma McCord",
    "Cryptozoology creatures",
    "Moon landing",
    "Big pharma",
    "Bilderberg",
    "Transhumanism",
    "Multiverse",
    "Stonehenge",
    "Chemtrails",
    "COINTELPRO",
    "BEKs",
    "Mandela effect",
    "Antarctica theories",
    "Majestic 12",
    "Skinwalkers",
    "Operation Northwoods",
    "Psyops",
    "Nibiru",
    "New World Order",
    "Red Squads",
    "Elisa Liam",
    "Atlantis",
]

